services:
  app:
    container_name: crochet_container
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - web:/wholeProject/static
  nginx:
    image: nginx
    container_name: nginx_container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - web:/static
      - /home/danilenko_e/2025-MAI-Backend-E-Danilenko/app/nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
  db:
    image: postgres
    container_name: db_container
    restart: always
    user: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend


volumes:
  pgdata:
  web:

networks:
  backend: